import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Cello_Staff_Group',
                'RH_Music_Staff',
                'RH_Music_Voice',
                'RH_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [149, 161, 172, 183, 194],
            ),
        ('duration', "2'03''"),
        ('final_measure_number', 207),
        ('first_measure_number', 149),
        ('phantom', True),
        ('segment_name', 'G'),
        ('segment_number', 6),
        ('start_clock_time', "12'13''"),
        ('stop_clock_time', "14'16''"),
        (
            'time_signatures',
            [
                '3/4',
                '1/3',
                '3/4',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                ],
            ),
        ]
    )
