import abjad
import ide

persist = abjad.OrderedDict(
    [
        (
            "alive_during_segment",
            [
                "Score",
                "Global_Context",
                "Global_Rests",
                "Global_Skips",
                "Music_Context",
                "Cello_Staff_Group",
                "RH_Music_Staff",
                "RH_Music_Voice",
                "RH_Rest_Voice",
                "Cello_Music_Staff",
                "Cello_Music_Voice",
                "Cello_Rest_Voice",
            ],
        ),
        (
            "persistent_indicators",
            abjad.OrderedDict(
                [
                    (
                        "Cello_Music_Staff",
                        [
                            ide.Momento(
                                context="Cello_Music_Voice",
                                prototype="abjad.Clef",
                                value="bass",
                            ),
                        ],
                    ),
                    (
                        "Cello_Staff_Group",
                        [
                            ide.Momento(
                                context="Cello_Music_Voice",
                                manifest="instruments",
                                value="Cello",
                            ),
                        ],
                    ),
                    (
                        "RH_Music_Staff",
                        [
                            ide.Momento(
                                context="RH_Music_Voice",
                                edition=abjad.Tag("-PARTS"),
                                prototype="baca.BarExtent",
                                value=7,
                            ),
                            ide.Momento(
                                context="RH_Music_Voice",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                            ide.Momento(
                                context="RH_Music_Voice",
                                prototype="baca.StaffLines",
                                value=7,
                            ),
                        ],
                    ),
                    (
                        "RH_Music_Voice",
                        [
                            ide.Momento(
                                context="RH_Music_Voice",
                                prototype="abjad.Dynamic",
                                value="p",
                            ),
                        ],
                    ),
                    (
                        "Score",
                        [
                            ide.Momento(
                                context="Global_Skips",
                                prototype="abjad.TimeSignature",
                                value="1/2",
                            ),
                            ide.Momento(
                                context="Global_Skips",
                                prototype="baca.Ritardando",
                                value={
                                    "hide": True,
                                },
                            ),
                        ],
                    ),
                ]
            ),
        ),
    ]
)
