import abjad
import huitzil


segment_maker = huitzil.FlightSegmentMaker(
    markup_leaves=False,
    name='flight E',
    pitches=[
        (0, 'A2'),
        ],
    staff_line_count=11
    )

segment_maker.notes = [
    (1, '3/4', 'fz'),
    '|',
    (1, '1/3', 'mfz'),
    '|',
    (1, '3/4', 'mfz'),
    '|',
    (2, '3/4', 'fz'),
    '|',
    (2, '1/3', 'mfz'),
    '|',
    (2, '3/4', 'mfz'),
    '|',
    (3, '2/4', None),
    '|',
    (2, '1/3', None),
    '|',
    (3, '3/4', 'fz'),
    '|',
    (3, '2/4', 'mfz'),
    '|',
    (2, '1/3', None),
    '|',
    (3, '3/4', 'fz'),
    '|',
    (3, '1/1', 'mfz'),
    '|',
    (4, '3/4', 'fz'),
    '|',
    (4, '1/3', 'mfz'),
    '|',
    (4, '3/4', 'mfz'),
    '|',
    (3, '2/4', None),
    '|',
    (4, '3/4', 'fz'),
    '|',
    (4, '1/3', 'mfz'),
    '|',
    (4, '1/1', 'mfz'),
    '|',

    # arrival at midpoint
    (5, '3/4', 'fz'),
    '|',
    (5, '1/3', 'mfz'),
    '|',
    (5, '3/4', 'fz'),
    '|',
    (6, '3/4', 'mfz'),
    '|',
    (6, '1/3', 'mfz'),
    '|',
    (6, '3/4', 'mfz'),
    '|',
    (7, '2/4', None),
    '|',
    (6, '1/3', None),
    '|',
    (7, '3/4', 'mfz'),
    '|',
    (7, '2/4', 'mfz'),
    '|',
    (6, '1/3', None),
    '|',
    (7, '3/4', 'fz'),
    '|',
    (7, '1/1', 'mfz'),
    '|',
    (8, '3/4', 'fz'),
    '|',
    (8, '1/3', 'mfz'),
    '|',
    (8, '3/4', 'mfz'),
    '|',
    (7, '2/4', None),
    '|',
    (8, '3/4', 'fz'),
    '|',
    (8, '1/3', 'mfz'),
    '|',
    (8, '1/1', 'mfz'),
    '|',

    # articulation of 9
    (9, '3/4', 'fz'),
    '|',
    (9, '1/3', 'mfz'),
    '|',
    (9, '3/4', 'mfz'),
    '|',
    (8, '2/4', None),
    '|',
    (9, '3/4', 'fz'),
    '|',
    (9, '1/3', 'mfz'),
    '|',
    (9, '1/1', 'mfz'),
    '|',

    # articulation of 10
    (10, '3/4', None),
    '|',
    (9, '2/4', None),
    '|',
    (10, '3/4', 'fz'),
    '|',
    (10, '1/3', 'mfz'),
    '|',
    (10, '1/1', 'mfz'),
    '|',

    # articulation of 11
    (11, '3/4', 'fz'),
    '|',
    (11, '1/3', 'mfz'),
    '|',
    (11, '3/4', 'mfz'),
    '|',
    (10, '2/4', None),
    '|',
    (11, '3/4', 'fz'),
    '|',
    (11, '1/3', 'mfz'),
    '|',
    (11, '1/1', 'fz'),
    '|',
    ]

segment_maker.glissando_break_indices = [
    ]

segment_maker.tempo_specifier = [
    (0, huitzil.tempi[66]),
    (3, abjad.Accelerando()),
    (8, huitzil.tempi[88]),
    (8, abjad.Ritardando()),
    (13, huitzil.tempi[66]),
    (17, abjad.Accelerando()),
    (19, huitzil.tempi[88]),
    (19, abjad.Ritardando()),
    (20, huitzil.tempi[66]),
    (23, abjad.Accelerando()),
    (28, huitzil.tempi[88]),
    (28, abjad.Ritardando()),
    (33, huitzil.tempi[66]),
    (37, abjad.Accelerando()),
    (39, huitzil.tempi[88]),
    (39, abjad.Ritardando()),
    (40, huitzil.tempi[66]),
    (44, abjad.Accelerando()),
    (46, huitzil.tempi[88]),
    (46, abjad.Ritardando()),
    (49, huitzil.tempi[66]),
    (52, abjad.Accelerando()),
    (54, huitzil.tempi[88]),
    (54, abjad.Ritardando()),
    (56, huitzil.tempi[66]),
    ]

segment_maker.tremolo_map = [
    ]

segment_maker.underlying_dynamics = [
    (0, 'p'),
    (0, '<'),
    (2, 'mp'),
    (2, '>'),
    (3, 'p'),
    (3, '<'),
    (5, 'mp'),
    (5, '>'),
    (8, 'p'),
    (8, '<'),
    (9, 'mp'),
    (9, '>'),
    (11, 'p'),
    (11, '<'),
    (12, 'mp'),
    (12, '>'),
    (13, 'p'),
    (13, '<'),
    (15, 'mp'),
    (15, '>'),
    (17, 'p'),
    (17, '<'),
    (19, 'mp'),
    (19, '>'),
    (20, 'p'),
    (20, '<'),
    (22, 'mp'),
    (22, '>'),
    (23, 'p'),
    (23, '<'),
    (25, 'mp'),
    (25, '>'),
    (28, 'p'),
    (28, '<'),
    (29, 'mp'),
    (29, '>'),
    (31, 'p'),
    (31, '<'),
    (32, 'mp'),
    (32, '>'),
    (33, 'p'),
    (33, '<'),
    (35, 'mp'),
    (35, '>'),
    (37, 'p'),
    (37, '<'),
    (39, 'mp'),
    (39, '>'),
    (40, 'p'),
    (40, '<'),
    (42, 'mp'),
    (42, '>'),
    (44, 'p'),
    (44, '<'),
    (46, 'mp'),
    (46, '>'),
    (49, 'p'),
    (49, '<'),
    (51, 'mp'),
    (51, '>'),
    (52, 'p'),
    (52, '<'),
    (54, 'mp'),
    (54, '>'),
    (56, 'p'),
    (56, '<'),
    (58, 'mp'),
    ]
