# -*- encoding: utf-8 -*-
from abjad.tools import indicatortools


time_signatures = [
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((9, 16)),
    indicatortools.TimeSignature((7, 16)),
    indicatortools.TimeSignature((6, 8)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((11, 16)),
    indicatortools.TimeSignature((5, 16)),
    indicatortools.TimeSignature((4, 4)),
    indicatortools.TimeSignature((6, 4)),
    indicatortools.TimeSignature((3, 4)),
    indicatortools.TimeSignature((4, 4)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((7, 16)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((8, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((5, 16)),
    indicatortools.TimeSignature((9, 16)),
    indicatortools.TimeSignature((5, 8)),
    indicatortools.TimeSignature((2, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((9, 16)),
    indicatortools.TimeSignature((7, 16)),
    indicatortools.TimeSignature((6, 8)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((11, 16)),
    indicatortools.TimeSignature((5, 16)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((2, 8)),
    indicatortools.TimeSignature((7, 8)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((7, 16)),
    indicatortools.TimeSignature((7, 16)),
    indicatortools.TimeSignature((8, 8)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((3, 8)),
    indicatortools.TimeSignature((4, 8)),
    indicatortools.TimeSignature((5, 16)),
    indicatortools.TimeSignature((9, 16)),
    indicatortools.TimeSignature((5, 8)),
    indicatortools.TimeSignature((2, 8)),
    ]