import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [
                1,
                5,
                9,
                13,
                17,
                22,
                27,
                32,
                37,
                42,
                47,
                51,
                55,
                67,
                79,
                84,
                88,
                93,
                100,
                107,
                113,
                118,
                123,
                129,
                134,
                141,
                152,
                158,
                165,
                174,
                187,
                200,
                205,
                212,
                220,
                227,
                233,
                240,
                247,
                254,
                ],
            ),
        ('catalog_number_suffix', 'A'),
        ('paper_size', 'arch a'),
        ('price', '$29 / \\euro 29'),
        ]
    )
