import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Cello_Staff_Group',
                'RH_Music_Staff',
                'RH_Music_Voice',
                'RH_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [240, 246, 254, 262],
            ),
        ('duration', "2'23''"),
        ('final_measure_number', 265),
        ('first_measure_number', 240),
        ('phantom', True),
        ('segment_name', 'I'),
        ('segment_number', 8),
        ('start_clock_time', "15'52''"),
        ('stop_clock_time', "18'15''"),
        (
            'time_signatures',
            [
                '1/1',
                '13/12',
                '1/1',
                '7/6',
                '53/30',
                '23/12',
                '1/1',
                '1/1',
                '3/4',
                '2/3',
                '22/15',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/3',
                '1/1',
                '4/5',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                ],
            ),
        ]
    )
