import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Cello_Music_Staff',
                'Global_Rests',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [1, 8, 14, 19, 26, 32, 39, 47, 52],
            ),
        ('duration', "5'05''"),
        ('final_measure_number', 54),
        ('first_measure_number', 1),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Cello_Music_Staff',
                        [
                            abjad.Momento(
                                context='Cello_Music_Voice',
                                manifest='instruments',
                                value='Cello',
                                ),
                            abjad.Momento(
                                context='Cello_Music_Voice',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='Global_Skips',
                                manifest='metronome_marks',
                                value='78',
                                ),
                            abjad.Momento(
                                context='Global_Skips',
                                prototype='abjad.TimeSignature',
                                value='3/4',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('phantom', True),
        ('segment_name', 'J'),
        ('segment_number', 11),
        ('start_clock_time', "0'00''"),
        ('stop_clock_time', "5'05''"),
        (
            'time_signatures',
            [
                '7/8',
                '15/16',
                '11/16',
                '7/8',
                '15/16',
                '15/16',
                '3/8',
                '1/1',
                '3/4',
                '7/8',
                '1/1',
                '3/4',
                '3/2',
                '5/4',
                '1/4',
                '2/1',
                '9/8',
                '7/8',
                '3/4',
                '5/8',
                '7/8',
                '1/2',
                '5/4',
                '1/1',
                '1/2',
                '5/4',
                '1/1',
                '1/2',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/2',
                '5/4',
                '13/16',
                '5/8',
                '5/4',
                '1/1',
                '5/16',
                '1/1',
                '9/16',
                '3/4',
                '7/8',
                '3/4',
                '7/8',
                '1/1',
                '1/4',
                '3/2',
                '1/1',
                '1/1',
                '9/4',
                '3/2',
                '1/1',
                '3/4',
                ],
            ),
        ]
    )
