import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Cello_Staff_Group',
                'RH_Music_Staff',
                'RH_Music_Voice',
                'RH_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [149, 161, 172, 183, 194],
            ),
        ('duration', "2'13''"),
        ('final_measure_number', 207),
        ('first_measure_number', 149),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Cello_Music_Staff',
                        [
                            abjad.Momento(
                                context='Cello_Music_Voice',
                                prototype='abjad.Clef',
                                value='bass',
                                ),
                            ],
                        ),
                    (
                        'Cello_Staff_Group',
                        [
                            abjad.Momento(
                                context='Cello_Music_Voice',
                                manifest='instruments',
                                value='Cello',
                                ),
                            ],
                        ),
                    (
                        'RH_Music_Staff',
                        [
                            abjad.Momento(
                                context='RH_Music_Voice',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='RH_Music_Voice',
                                prototype='abjad.PersistentOverride',
                                value=abjad.PersistentOverride(
                                    attribute='bar_extent',
                                    context='Staff',
                                    grob='bar_line',
                                    value=(-5, 5),
                                    ),
                                ),
                            abjad.Momento(
                                context='RH_Music_Voice',
                                prototype='baca.StaffLines',
                                value=11,
                                ),
                            ],
                        ),
                    (
                        'RH_Music_Voice',
                        [
                            abjad.Momento(
                                context='RH_Music_Voice',
                                prototype='abjad.Dynamic',
                                value='ff',
                                ),
                            ],
                        ),
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='Global_Skips',
                                manifest='metronome_marks',
                                value='66',
                                ),
                            abjad.Momento(
                                context='Global_Skips',
                                prototype='abjad.TimeSignature',
                                value='1/1',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('phantom', True),
        ('segment_name', 'P'),
        ('segment_number', 16),
        ('start_clock_time', "12'08''"),
        ('stop_clock_time', "14'21''"),
        (
            'time_signatures',
            [
                '3/4',
                '1/3',
                '3/4',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/2',
                '1/3',
                '3/4',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                '3/4',
                '1/3',
                '3/4',
                '1/2',
                '3/4',
                '1/3',
                '1/1',
                ],
            ),
        ]
    )
