# -*- encoding: utf-8 -*-
from abjad import *
from huitzil import makers
from huitzil import materials
from huitzil.segments.abbreviations import *


segment_maker = makers.FlightSegmentMaker(
    markup_leaves=False,
    name='flight E',
    pitches=[
        (0, 'A2'),
        ],
    staff_line_count=11
    )

segment_maker.notes = [
    (1, '3/4', fz),
    bar,
    (1, '1/3', mfz),
    bar,
    (1, '3/4', mfz),
    bar,
    (2, '3/4', fz),
    bar,
    (2, '1/3', mfz),
    bar,
    (2, '3/4', mfz),
    bar,
    (3, '2/4', None),
    bar,
    (2, '1/3', None),
    bar,
    (3, '3/4', fz),
    bar,
    (3, '2/4', mfz),
    bar,
    (2, '1/3', None),
    bar,
    (3, '3/4', fz),
    bar,
    (3, '1/1', mfz),
    bar,
    (4, '3/4', fz),
    bar,
    (4, '1/3', mfz),
    bar,
    (4, '3/4', mfz),
    bar,
    (3, '2/4', None),
    bar,
    (4, '3/4', fz),
    bar,
    (4, '1/3', mfz),
    bar,
    (4, '1/1', mfz),
    bar,

    # arrival at midpoint
    (5, '3/4', fz),
    bar,
    (5, '1/3', mfz),
    bar,
    (5, '3/4', fz),
    bar,
    (6, '3/4', mfz),
    bar,
    (6, '1/3', mfz),
    bar,
    (6, '3/4', mfz),
    bar,
    (7, '2/4', None),
    bar,
    (6, '1/3', None),
    bar,
    (7, '3/4', mfz),
    bar,
    (7, '2/4', mfz),
    bar,
    (6, '1/3', None),
    bar,
    (7, '3/4', fz),
    bar,
    (7, '1/1', mfz),
    bar,
    (8, '3/4', fz),
    bar,
    (8, '1/3', mfz),
    bar,
    (8, '3/4', mfz),
    bar,
    (7, '2/4', None),
    bar,
    (8, '3/4', fz),
    bar,
    (8, '1/3', mfz),
    bar,
    (8, '1/1', mfz),
    bar,

    # articulation of 9
    (9, '3/4', fz),
    bar,
    (9, '1/3', mfz),
    bar,
    (9, '3/4', mfz),
    bar,
    (8, '2/4', None),
    bar,
    (9, '3/4', fz),
    bar,
    (9, '1/3', mfz),
    bar,
    (9, '1/1', mfz),
    bar,

    # articulation of 10
    (10, '3/4', None),
    bar,
    (9, '2/4', None),
    bar,
    (10, '3/4', fz),
    bar,
    (10, '1/3', mfz),
    bar,
    (10, '1/1', mfz),
    bar,

    # articulation of 11
    (11, '3/4', fz),
    bar,
    (11, '1/3', mfz),
    bar,
    (11, '3/4', mfz),
    bar,
    (10, '2/4', None),
    bar,
    (11, '3/4', fz),
    bar,
    (11, '1/3', mfz),
    bar,
    (11, '1/1', fz),
    bar,
    ]

segment_maker.glissando_break_indices = [
    ]

segment_maker.tempo_map = [
    (0, quarter_66),
    (3, Accelerando()),
    (8, quarter_88),
    (8, Ritardando()),
    (13, quarter_66),
    (17, Accelerando()),
    (19, quarter_88),
    (19, Ritardando()),
    (20, quarter_66),
    (23, Accelerando()),
    (28, quarter_88),
    (28, Ritardando()),
    (33, quarter_66),
    (37, Accelerando()),
    (39, quarter_88),
    (39, Ritardando()),
    (40, quarter_66),
    (44, Accelerando()),
    (46, quarter_88),
    (46, Ritardando()),
    (49, quarter_66),
    (52, Accelerando()),
    (54, quarter_88),
    (54, Ritardando()),
    (56, quarter_66),
    ]

segment_maker.tremolo_map = [
    ]

segment_maker.underlying_dynamics = [
    (0, p),
    (0, crescendo),
    (2, mp),
    (2, decrescendo),
    (3, p),
    (3, crescendo),
    (5, mp),
    (5, decrescendo),
    (8, p),
    (8, crescendo),
    (9, mp),
    (9, decrescendo),
    (11, p),
    (11, crescendo),
    (12, mp),
    (12, decrescendo),
    (13, p),
    (13, crescendo),
    (15, mp),
    (15, decrescendo),
    (17, p),
    (17, crescendo),
    (19, mp),
    (19, decrescendo),
    (20, p),
    (20, crescendo),
    (22, mp),
    (22, decrescendo),
    (23, p),
    (23, crescendo),
    (25, mp),
    (25, decrescendo),
    (28, p),
    (28, crescendo),
    (29, mp),
    (29, decrescendo),
    (31, p),
    (31, crescendo),
    (32, mp),
    (32, decrescendo),
    (33, p),
    (33, crescendo),
    (35, mp),
    (35, decrescendo),
    (37, p),
    (37, crescendo),
    (39, mp),
    (39, decrescendo),
    (40, p),
    (40, crescendo),
    (42, mp),
    (42, decrescendo),
    (44, p),
    (44, crescendo),
    (46, mp),
    (46, decrescendo),
    (49, p),
    (49, crescendo),
    (51, mp),
    (51, decrescendo),
    (52, p),
    (52, crescendo),
    (54, mp),
    (54, decrescendo),
    (56, p),
    (56, crescendo),
    (58, mp),
    ]