import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [233, 241, 249, 257],
            ),
        ('duration', "1'36''"),
        ('final_measure_number', 264),
        ('first_measure_number', 233),
        ('segment_name', 'H'),
        ('segment_number', 8),
        ('start_clock_time', "15'44''"),
        ('stop_clock_time', "17'20''"),
        (
            'time_signatures',
            [
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                ],
            ),
        ]
    )
