import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Cello_Staff_Group',
                'RH_Music_Staff',
                'RH_Music_Voice',
                'RH_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [208, 216, 224, 232],
            ),
        ('duration', "1'36''"),
        ('final_measure_number', 239),
        ('first_measure_number', 208),
        ('phantom', True),
        ('segment_name', 'H'),
        ('segment_number', 7),
        ('start_clock_time', "14'16''"),
        ('stop_clock_time', "15'52''"),
        (
            'time_signatures',
            [
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '3/4',
                '3/4',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                '1/1',
                ],
            ),
        ]
    )
